[package]
name = "codebar"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "codebar_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-autostart = "2.5.1"
tauri-plugin-notification = "2.3.3"
tauri-plugin-positioner = { version = "2.3.3", features = ["tray-icon"] }
tokio = { version = "1.53.1", features = ["time", "sync", "macros"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "json", "query"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.62.2", features = ["Win32_Security_Cryptography", "Win32_System_Memory", "Win32_Foundation"] }

